title: Флот России
email: support@superuser.su
author: superuser
description: >
  история, традиции, слава
baseurl: "/"
url: "https://www.flot.su"
link: "https://www.flot.su"
# Build settings
excerpt_separator: <!--more-->
markdown: kramdown
kramdown:
  auto_ids: false
include:
  - public
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - src

sass:
    style: compressed

collections:
    front-page:
        output: true
plugins:
  - jekyll-feed
  - jekyll-sitemap


